AmazonWebAppMVC/Controllers/HomeController.cs
using AmazonWebAppMVC.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace AmazonWebAppMVC.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly AmazonWebAppMVCContext _context;
        public HomeController(ILogger<HomeController> logger, AmazonWebAppMVCContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index(string? SearchTerm,int? CategoryId)
        {
            _logger.LogInformation("HomeController::Index({searchTerm},{categoryId}) called",SearchTerm,CategoryId);
            if(_context.Product == null || _context.Category == null)
            {
                _logger.LogError("HomeController::Index() _context.Product or _context.Category is null");
                return NotFound();
            }
            
            var products = from p in _context.Product.Include(p => p.Categorie) select p;
            
            if(!string.IsNullOrEmpty(SearchTerm))
            {
                products = products.Where(p => p.Name.Contains(SearchTerm));
            }

            if(CategoryId != null)
            {
                _logger.LogInformation("HomeController::Index() CategoryId = " + CategoryId);
                products = products.Where(p => p.CategoryId == CategoryId);
            }
            
            
            var categories = await _context.Category.ToListAsync();
            ViewData["Categories"] = new SelectList(categories, "Id", "Name");
            _logger.LogInformation("HomeController::Index() products number = " + products.Count());
            return View(await products.ToListAsync());
        }

    
    }
}

AmazonWebAppMVC/Controllers/PanierController.cs
using AmazonWebAppMVC.Data;
using AmazonWebAppMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace AmazonWebAppMVC.Controllers
{
    [Authorize(Roles= "Client")]
    public class PanierController : Controller
    {
        private readonly AmazonWebAppMVCContext _context;
        private readonly ILogger _logger;
        private const string SessionKeyName = ".Order.Session";
        
        public PanierController(AmazonWebAppMVCContext context, ILogger<PanierController> logger)
        {
            _context = context;
            _logger = logger;
        }


        public IActionResult Index()
        {


            //get cart from session or create new cart using serialization
            _logger.LogInformation("PanierController::Index() called");
            var item = HttpContext.Session.GetString(SessionKeyName);
            _logger.LogInformation("PanierController::Index() item = " + item);
            Order order = item == null ? new Order() : JsonSerializer.Deserialize<Order>(item);
            // get the products from the database
            foreach (OrderItem orderItem in order.OrderItems)
            {
                orderItem.Product = _context.Product.Find(orderItem.ProductId);
            }
            _logger.LogInformation("PanierController::Index() order = " + order);
            return View("Index",order);
        }

        // create a method to add a product to the cart
        public IActionResult AddToCart(int productId)
        {
           

            //get cart from session or create new cart using serialization
            var item = HttpContext.Session.GetString(SessionKeyName);
            Order order = item == null ? new Order() : JsonSerializer.Deserialize<Order>(item);
            _logger.LogInformation("PanierController::AddToCart() Order before = " + order);
            //product price
            var product = _context.Product.Find(productId);
            _logger.LogInformation("PanierController::AddToCart() product = " + product);
            //add product to cart
            order.AddItem(productId, product.Price);
            //refresh total
            order.Total += (int)product.Price;
            //save cart to session
            _logger.LogInformation("PanierController::AddToCart() Order after = " + order);
            HttpContext.Session.SetString(SessionKeyName, JsonSerializer.Serialize(order));

            //redirect to cart page
            return RedirectToAction("Index");
        }
    }
}

AmazonWebAppMVC/Views/Home/Index.cshtml
@model IEnumerable<AmazonWebAppMVC.Models.Product>

@{
    ViewData["Title"] = "Home";

    string IsClient() => User.Identity.IsAuthenticated && User.IsInRole("Client") ? "" : "hidden";
}

<div class="flex justify-center mt-5">
    <form class="flex">
        <select name="CategoryId" class="p-2 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500" asp-items="@((SelectList)ViewData["Categories"])">
            <option value="">All</option>
        </select>
        <input type="text" name="SearchTerm" class="p-2 border border-gray-300 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full placeholder-gray-400" placeholder="Enter Product Name...">
        <button type="submit" class="py-2 px-4 bg-blue-500 text-white rounded-lg ml-2">Search</button>
    </form>
</div>
<div class="flex flex-wrap gap-5 mt-5">
    @foreach (var item in Model)
    {
        <div class="bg-white border rounded-lg shadow-lg hover:shadow-xl transition duration-300 ease-in-out transform hover:scale-105 ">
            <div class="relative overflow-hidden rounded-t-lg">
                <img src="~/images/@item.ImageUrl" alt="@item.Name" class="w-full h-52 object-contain">
            </div>
            <div class="p-4">
                <h3 class="text-xl font-semibold text-gray-800">@item.Name</h3>
                <p class="text-gray-600 mt-2 mb-2" style="width:350px;max-width:350px">@item.Description</p>
                <span class="badge bg-secondary">@item.Categorie.Name</span>
                <div class="align-items-center flex justify-content-between mt-4">
                    <p class="font-sans md:font-serif text-blue-600">$ @item.Price</p>
                    <form asp-controller="Panier" asp-action="AddToCart" class="@IsClient() ">
                        <input type="hidden" name="productId" value="@item.Id" />
                        <button class="bg-yellow-300 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded">
                            Add To Cart
                        </button>
                    </form>
                </div>
            </div>
        </div>
    }
</div>